=== rubencit04/actividadesLGDM/DTD_XSD/4/emp.dtd
<!ELEMENT empresa (nombre, nif, española, capitalsocial, direccion, empleados)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT española (#PCDATA)>
<!ELEMENT capitalsocial (euros | dolares | yenes)>
<!ELEMENT euros (#PCDATA)>
<!ELEMENT dolares (#PCDATA)>
<!ELEMENT yenes (#PCDATA)>
<!ELEMENT direccion (via, nombre, cp, pais)>
<!ELEMENT via (#PCDATA)> 
<!ELEMENT cp (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (nombre, apellidos, dni, extranjero, nacimiento, salario, direccion2, casado?)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT extranjero (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT salario (#PCDATA)>
<!ELEMENT casado (#PCDATA)>
<!ELEMENT direccion2 (calle, pais)>
<!ELEMENT calle (#PCDATA)>
<!ENTITY españa SYSTEM "ESPAÑA">

=== rubencit04/actividadesLGDM/DTD_XSD/4/empresadtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "emp.dtd">
<empresa>
    <nombre>upgrade</nombre>
    <nif>14141</nif>
    <espa単ola>si</espa単ola>
    <capitalsocial>
        <euros>2999.15</euros>
    </capitalsocial>
    <direccion>
        <via>granvia</via>
        <nombre>granvia</nombre>
        <cp>21</cp>
        <pais>espa単a</pais>
    </direccion>
    <empleados>
        <empleado>
            <nombre>pedro</nombre>
            <apellidos>lopez</apellidos>
            <dni>5248234723J</dni>
            <extranjero>no</extranjero>
            <nacimiento>20/09/1993</nacimiento>
            <salario>2000</salario>
            <direccion2>
                <calle>callao</calle>
                <pais>espa単a</pais>
            </direccion2>
            <casado>no</casado>
        </empleado>
    </empleados>
</empresa>
