<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
<!ELEMENT biblioteca (nombre, seccion+)>
<!ATTLIST biblioteca id ID #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT seccion (libro+)>
<!ATTLIST seccion categoria (Novela | Ciencia_ficción | Aventura | Historia ) >
<!ELEMENT libro (titulo, autor, resumen?, editorial)>
<!ATTLIST libro id ID #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>

<!ELEMENT editorial (nombre, ciudad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
]>
<biblioteca codigo="B_67">
    <nombre>Biblioteca nacional</nombre>
    <seccion categoria="Aventura">
        <libro id="L1">
            <titulo>El señor de los anillos</titulo>
            <autor>J.R.R. Tolkien</autor>
            <resumen>Un viaje épico para destruir un anillo mágico.</resumen>
            <editorial>
                <nombre>Editorial Fantástica</nombre>
                <ciudad>Barcelona</ciudad>
            </editorial>
        </libro>
        <libro id="L2">
            <titulo>Harry Potter y la piedra filosofal</titulo>
            <autor>J.K. Rowling</autor>
            <anio>1997</anio>
            <resumen>Las aventuras de un joven mago en Hogwarts.</resumen>
            <editorial>
                <nombre>Ediciones Mágicas</nombre>
                <ciudad>Londres</ciudad>
            </editorial>
        </libro>
    </seccion>
    <seccion categoria="Novela" pasillo="P3">
        <libro id="L3">
            <titulo>Cien años de soledad</titulo>
            <autor>Gabriel García Márquez</autor>
            <anio>1967</anio>
            <resumen>La historia de la familia Buendía en Macondo.</resumen>
            <editorial>
                <nombre>Ediciones Macondo</nombre>
                <ciudad>Bogotá</ciudad>
            </editorial>
        </libro>
    </seccion>
    <seccion categoria="Ciencia ficción">
        <libro id="L4">
            <titulo>1984</titulo>
            <autor>George Orwell</autor>
            <resumen>Un futuro distópico donde el pensamiento está controlado.</resumen>
            <editorial>
                <codigo>ED45TR</codigo>
                <nombre>Editorial Distopía</nombre>
                <ciudad>Londres</ciudad>
            </editorial>
        </libro>
        <libro id="L5">
            <titulo>Fundación</titulo>
            <autor>Isaac Asimov</autor>
            <anio>1951</anio>
            <resumen>La historia de la Fundación para prever el futuro galáctico.</resumen>
            <editorial>
                <nombre>Ediciones Galácticas</nombre>
                <ciudad>Nueva York</ciudad>
            </editorial>
        </libro>
    </seccion>
</biblioteca>