=== rubencit04/actividadesLGDM/Restriccionesexpresionesregulares/ciud.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ciudad">
        <xs:complexType>
            <xs:sequence>
                <element name="nombre">
                    <simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z][a-zA-Z]{2,19}" />
                        </xs:restriction>
                    </simpleType>
                </element>
                <element name="codigo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Za-z]{2}-\d{2,5}" />
                        </xs:restriction>
                    </xs:simpleType>
                </element>
                <element name="poblacion">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minExclusive value="100"></xs:minExclusive>
                            <xs:maxExclusive value="100000"></xs:maxExclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </element>
                <element name="alcalde">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-zA-Z]{0,10}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="apellidos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[A-Z][a-zA-Z ]{0,24}([ ][A-Z][a-zA-Z ]{0,24})?" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minExclusive value="18"></xs:minExclusive>
                                        <xs:maxExclusive value="120"></xs:maxExclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="[+]\d+[34]\d{9}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tarjeta_credito" type="xs:integer">
                            </xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <restriction base="xs:string">
                                        <pattern value="[^@]+@[^\.]+\..+"></pattern>
                                    </restriction>
                                </xs:simpleType>
                            </xs:element>
                            <element name="funcionarios">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="funcionario" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="[A-Z0-9]{1,10}"></xs:pattern>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </element>
                        </xs:sequence>
                    </xs:complexType>
                </element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rubencit04/actividadesLGDM/Restriccionesexpresionesregulares/ciudad.xml
<?xml version="1.0" encoding="UTF-8"?>
<ciudad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "ciud.xsd">
<nombre>Espana</nombre>
<codigo>LI-2342</codigo>
<poblacion>73613</poblacion>
<alcalde>
    <nombre>Alejandro</nombre>
    <apellidos>Lopez Gomez</apellidos>
    <edad>20</edad>
    <telefono>+34839123927</telefono>
    <tarjeta_credito>312314</tarjeta_credito>
    <email>pabloalboran@gmail.com</email>
</alcalde>
<funcionarios>
    <funcionario>
        <id></id>
        <nombre></nombre>
        <apellidos></apellidos>
        <codigo_postal></codigo_postal>
        <fecha_nacimiento></fecha_nacimiento>
        <contraseña></contraseña>
        <numero_cuenta></numero_cuenta>
    </funcionario>
</funcionarios>
</ciudad>
